---

version: '3.9'
networks:
  icinet:
    enable_ipv6: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.default_bridge: 'true'
      com.docker.network.bridge.enable_icc: 'true'
      com.docker.network.bridge.enable_ip_masquerade: 'true'
      com.docker.network.bridge.host_binding_ipv4: '0.0.0.0'
      com.docker.network.bridge.name: 'docker0'
      com.docker.network.driver.mtu: '1500'
    ipam:
      driver: default
      config:
      - subnet: fd00:dead:beef::/48

services:
  postgres:
    image: postgres:13-bullseye
    hostname: pgsql
    container_name: pgsql
    restart: always
    networks:
      icinet:
    environment:
      POSTGRES_PASSWORD: "sec-pwd"

  icinga2:
    image: 'registry.gitlab.ics.muni.cz:443/monitoring/icinga:stable'
    container_name: icinga2
    restart: always
    hostname: 'icinga2'
    networks:
      icinet:
    ports:
      - "5665:5665"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 65536
        hard: 65536
    volumes:
      - "./icinga/etc:/etc/icinga2"
      - "./icinga/lib:/var/lib/icinga2"
    environment:
      DEFAULT_PGSQL_PASS:       "sec-pwd"
      PGSQL_ROOT_PASS:          "sec-pwd"
      ICINGA2_RLIMIT_PROCESSES: "65536"
      ICINGA2_RLIMIT_FILES:     "65536"

  icingaweb2:
    image: 'registry.gitlab.ics.muni.cz:443/monitoring/icingaweb:stable'
    container_name: icingaweb2
    restart: always
    hostname: 'icingaweb2'
    networks:
      icinet:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./icingaweb/etc:/etc/icingaweb2"
      - "./icingaweb/php:/var/lib/php/sessions"
    environment:
      DEFAULT_PGSQL_PASS:    "sec-pwd"
      PGSQL_ROOT_PASS:       "sec-pwd"
      ICINGAWEB2_DIRECTOR:   "0"
      ICINGAWEB2_DEPENDENCY: "0"
      APACHE2_SERVER_NAME:   "icingaweb2"

...
