#!/bin/bash

. /opt/helpers

APACHE2_OIDC_ENABLE=${APACHE2_OIDC_ENABLE=:-"false"}

if evaluate_boolean "${APACHE2_OIDC_ENABLE}"; then
	echo "Apache2: Setting up OpenID Connect"

	[[ -v APACHE2_OIDC_AUTH_REQUEST_PARAMS ]] && APACHE2_OIDC_AUTH_REQ_PARAMS="OIDCAuthRequestParams \"${APACHE2_OIDC_AUTH_REQUEST_PARAMS}\""
	[[ -v APACHE2_OIDC_CACHE_SHM_MAX ]] && APACHE2_OIDC_CACHE_SHM_MAX="OIDCCacheShmMax \"${APACHE2_OIDC_CACHE_SHM_MAX}\""
	[[ -v APACHE2_OIDC_CACHE_SHM_ENTRY_MAX ]] && APACHE2_OIDC_CACHE_SHM_ENTRY_MAX="OIDCCacheShmEntrySizeMax \"${APACHE2_OIDC_CACHE_SHM_ENTRY_MAX}\""
	[[ -v APACHE2_OIDC_CACHE_FILE_CLEAN_INTERVAL ]] && APACHE2_OIDC_CACHE_FILE_CLEAN_INTERVAL="OIDCCacheFileCleanInterval \"${APACHE2_OIDC_CACHE_FILE_CLEAN_INTERVAL}\""
	[[ -v APACHE2_OIDC_MEMCACHE_SERVERS ]] && APACHE2_OIDC_MEMCACHE_SERVERS="OIDCMemCacheServers \"${APACHE2_OIDC_MEMCACHE_SERVERS}\""
	[[ -v APACHE2_OIDC_REDIS_SERVER ]] && APACHE2_OIDC_REDIS_SERVER="OIDCRedisCacheServer \"${APACHE2_OIDC_REDIS_SERVER}\""
	[[ -v APACHE2_OIDC_REDIS_PASSWORD ]] && APACHE2_OIDC_REDIS_PASSWORD="OIDCRedisCachePassword \"${APACHE2_OIDC_REDIS_PASSWORD}\""
	[[ -v APACHE2_OIDC_REDIS_DB ]] && APACHE2_OIDC_REDIS_DB="OIDCRedisCacheDatabase \"${APACHE2_OIDC_REDIS_DB}\""
	[[ -v APACHE2_OIDC_REDIS_TIMEOUT ]] && APACHE2_OIDC_REDIS_TIMEOUT="OIDCRedisCacheConnectTimeout \"${APACHE2_OIDC_REDIS_TIMEOUT}\""
	[[ -v APACHE2_OIDC_XFORWARDED_HEADERS ]] && APACHE2_OIDC_XFORWARDED_HEADERS="OIDCXForwardedHeaders \"${APACHE2_OIDC_XFORWARDED_HEADERS}\""

	cat > /etc/apache2/conf-available/oidc-auth.conf <<-END
	OIDCProviderMetadataRefreshInterval ${APACHE2_OIDC_METADATA_REFRESH:-3600}
	OIDCProviderMetadataURL $APACHE2_OIDC_METADATA
	OIDCClientID $APACHE2_OIDC_CLIENTID
	OIDCClientSecret $APACHE2_OIDC_CLIENTSECRET
	OIDCScope "${APACHE2_OIDC_SCOPE:-openid profile}"
	OIDCRedirectURI ${APACHE2_OIDC_REDIRECT_URI:-/callback}
	OIDCRemoteUserClaim $APACHE2_OIDC_REMOTE_USER_CLAIM
	OIDCCryptoPassphrase $APACHE2_OIDC_PASSPHRASE
	OIDCSSLValidateServer ${APACHE2_OIDC_SSL_VALIDATE_SERVER:-On}
	OIDCOAuthSSLValidateServer  ${APACHE2_OIDC_AUTHSSL_VALIDATE_SERVER:-On}
	OIDCInfoHook ${APACHE2_OIDC_INFOHOOK:-iat access_token access_token_expires id_token userinfo refresh_token session}
	OIDCCookiePath ${APACHE2_OIDC_COOKIE_PATH:-/}
	OIDCPassRefreshToken ${APACHE2_OIDC_REFRESH_TOKEN:-On}
	OIDCSessionInactivityTimeout ${APACHE2_OIDC_SESSION_INACTIVITY_TIMEOUT:-86400}
	OIDCSessionType ${APACHE2_OIDC_SESSION_TYPE:-server-cache}
	OIDCSessionMaxDuration ${APACHE2_OIDC_SESSION_MAX_DURATION:-86400}
	OIDCCacheType ${APACHE2_OIDC_CACHE_TYPE:-file}
	OIDCSessionCacheFallbackToCookie ${APACHE2_OIDC_CACHE_FALLBACK:-Off}
	OIDCCacheDir ${APACHE2_OIDC_CACHE_DIR:-/var/cache/apache2/mod_auth_openidc/cache}
	OIDCCacheEncrypt ${APACHE2_OIDC_CACHE_ENCRYPT:-Off}
	OIDCStateMaxNumberOfCookies 10 true
	${APACHE2_OIDC_AUTH_REQ_PARAMS}
	${APACHE2_OIDC_CACHE_SHM_MAX}
	${APACHE2_OIDC_CACHE_SHM_ENTRY_MAX}
	${APACHE2_OIDC_CACHE_FILE_CLEAN_INTERVAL}
	${APACHE2_OIDC_MEMCACHE_SERVERS}
	${APACHE2_OIDC_REDIS_SERVER}
	${APACHE2_OIDC_REDIS_PASSWORD}
	${APACHE2_OIDC_REDIS_DB}
	${APACHE2_OIDC_REDIS_TIMEOUT}
	${APACHE2_OIDC_XFORWARDED_HEADERS}

	<Location /icingaweb2/authentication/logout>
		Redirect https://%{HTTP_HOST}$APACHE2_OIDC_REDIRECT_URI?logout=https://%{HTTP_HOST}
	</Location>

	<Location /callback>
		Header always set Cache-Control "no-cache, no-store, max-age=0, must-revalidate"
		Header always set Pragma no-cache
		Header always set Expires 0
		AuthType openid-connect
		Require valid-user
	</Location>

	<Location ~ '^((?!/server-status).)*$'>
		AuthType openid-connect
		Require valid-user
	</Location>
	END

	a2enmod -q headers auth_openidc >/dev/null 2>&1
	echo -e "Apache2: Enabled OpenID Connect\n"
else
	echo '' > /etc/apache2/conf-available/oidc-auth.conf

	a2dismod -q auth_openidc >/dev/null 2>&1 || true
fi
