#!/bin/bash

. /opt/helpers

if evaluate_boolean "${ICINGAWEB2_FEATURE_PHP_FPM}"; then

	PHP_FPM_CONFIG_PATH=/etc/php/${PHP_VERSION}/fpm/conf.d/
	PHP_FPM_CONFIG=${PHP_FPM_CONFIG_PATH}/docker.ini
	PHP_FPM_CONFIG_POOL_PATH=/etc/php/${PHP_VERSION}/fpm/pool.d/
	PHP_FPM_CONFIG_POOL=${PHP_FPM_CONFIG_POOL_PATH}/www.conf

	echo "PHP-FPM: Preparing"

	ini_set ${PHP_FPM_CONFIG} opcache opcache.enable ${PHP_FPM_OPCACHE_ENABLE:-1}
	ini_set ${PHP_FPM_CONFIG} opcache opcache.enable_cli ${PHP_FPM_OPCACHE_ENABLE_CLI:-0}
	ini_set ${PHP_FPM_CONFIG} opcache opcache.fast_shutdown ${PHP_FPM_OPCACHE_FAST_SHUTDOWN:-1}
	ini_set ${PHP_FPM_CONFIG} opcache opcache.memory_consumption ${PHP_FPM_OPCACHE_MEMORY_CONSUMPTION:-256M}
	ini_set ${PHP_FPM_CONFIG} opcache opcache.interned_strings_buffer ${PHP_FPM_OPCACHE_STRINGS_BUFFER:-16}
	ini_set ${PHP_FPM_CONFIG} opcache opcache.max_accelerated_files ${PHP_FPM_OPCACHE_MAX_ACCELERATED:-10000}
	ini_set ${PHP_FPM_CONFIG} opcache opcache.revalidate_freq ${PHP_FPM_OPCACHE_REVALIDATE_FREQ:-60}
	ini_set ${PHP_FPM_CONFIG} Session session.use_strict_mode 1
	ini_set ${PHP_FPM_CONFIG} www post_max_size ${PHP_FPM_MAX_POST:-16M}
	ini_set ${PHP_FPM_CONFIG} www upload_max_filesize ${PHP_FPM_MAX_UPLOAD:-16M}
	ini_set ${PHP_FPM_CONFIG} www max_execution_time ${PHP_FPM_MAX_EXECUTION_TIME:-10800}
	ini_set ${PHP_FPM_CONFIG} www max_input_time ${PHP_FPM_MAX_INPUT_TIME:-3600}
	ini_set ${PHP_FPM_CONFIG} www expose_php ${PHP_FPM_EXPOSE:-Off}
	ini_set ${PHP_FPM_CONFIG} www memory_limit ${PHP_FPM_MEMORY_LIMIT:-256M}

	ini_set ${PHP_FPM_CONFIG_POOL} www access.log /dev/stdout
	ini_set ${PHP_FPM_CONFIG_POOL} www clear_env no
	ini_set ${PHP_FPM_CONFIG_POOL} www user ""
	ini_set ${PHP_FPM_CONFIG_POOL} www group ""
	ini_set ${PHP_FPM_CONFIG_POOL} www catch_workers_output yes
	ini_set ${PHP_FPM_CONFIG_POOL} www decorate_workers_output no
	ini_set ${PHP_FPM_CONFIG_POOL} www listen /run/php/php${PHP_VERSION}-fpm.sock
	ini_set ${PHP_FPM_CONFIG_POOL} www pm ${PHP_FPM_PM:-dynamic}
	ini_set ${PHP_FPM_CONFIG_POOL} www pm.start_servers ${PHP_FPM_PM_SERVERS:-10}
	ini_set ${PHP_FPM_CONFIG_POOL} www pm.min_spare_servers ${PHP_FPM_PM_MIN:-10}
	ini_set ${PHP_FPM_CONFIG_POOL} www pm.max_spare_servers ${PHP_FPM_PM_MAX:-32}
	ini_set ${PHP_FPM_CONFIG_POOL} www pm.process_idle_timeout ${PHP_FPM_PM_IDLE:-30}
	ini_set ${PHP_FPM_CONFIG_POOL} www pm.max_children ${PHP_FPM_PM_CHILDREN:-48}
	ini_set ${PHP_FPM_CONFIG_POOL} www pm.max_requests ${PHP_FPM_PM_REQUESTS:-0}

	echo "Apache2: Enabling mpm_event"
	cat > /etc/apache2/mods-available/mpm_event.conf <<-END
	<IfModule mpm_event_module>
		StartServers		${APACHE2_EVENT_SERVERS:-3}
		MinSpareThreads		${APACHE2_EVENT_MIN_SPARE:-75}
		MaxSpareThreads		${APACHE2_EVENT_MAX_SPARE:-250}
		ThreadLimit		${APACHE2_EVENT_THREADS:-64}
		ThreadsPerChild		${APACHE2_EVENT_CHILD_THREADS:-25}
		MaxRequestWorkers	${APACHE2_EVENT_WORKERS:-400}
		MaxConnectionsPerChild	${APACHE2_EVENT_CONN_PER_CHILD:-0}
	</IfModule>
	END

	a2dismod -q php${PHP_VERSION} mpm_prefork >/dev/null 2>&1
	a2enconf -q php${PHP_VERSION}-fpm >/dev/null 2>&1
	a2enmod  -q mpm_event setenvif proxy_fcgi http2 >/dev/null 2>&1

	echo "Apache2: Enabling HTTP/2"
        cat > /etc/apache2/mods-available/http2.conf <<-END
	<IfModule !mpm_prefork>
		Protocols h2 h2c
		H2Direct on
		ProtocolsHonorOrder on
		H2SerializeHeaders off
	</IfModule>
	END

	echo -e "PHP-FPM configured\n"
fi
